## Introduction to Pandas and NumPy

In [28]:
import pandas as pd
import numpy as np

In [62]:
# load the data
df=pd.read_csv("C:\\Users\\KMC\\Desktop\\pandas\\titanic.csv")

In [64]:
# Explore the Data
print(df.head()) 

   PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  


In [66]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB
None


In [74]:
df.sample(2)

PassengerId  Survived  Pclass                      Name   Sex   Age  \
101          993         0       2        Weisz, Mr. Leopold  male  27.0   
34           926         0       1  Mock, Mr. Philipp Edmund  male  30.0   

     SibSp  Parch  Ticket   Fare Cabin Embarked  
101      1      0  228414  26.00   NaN        S  
34       1      0   13236  57.75   C78        C

In [77]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [ ]:
# handle missing values

In [100]:
#Drop Missing Values
df_clean = df.dropna()

In [102]:
print(df_clean.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64


In [104]:
# Remove duplicates
df.drop_duplicates(inplace=True)

In [106]:
df.sample(2)

PassengerId  Survived  Pclass  \
345         1237         1       3   
272         1164         1       1   

                                              Name     Sex   Age  SibSp  \
345                    Abelseth, Miss. Karen Marie  female  16.0      0   
272  Clark, Mrs. Walter Miller (Virginia McDowell)  female  26.0      1   

     Parch  Ticket      Fare Cabin Embarked  
345      0  348125    7.6500   NaN        S  
272      0   13508  136.7792   C89        C

In [108]:
#: Create NumPy Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [110]:
#Perform Mathematical Operations
print(a + b) 
print(a - b) 
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [112]:
print(np.mean(a))
print(np.max(b)) 
print(np.min(a))
print(np.sum(a)) 

2.0
6
1
6


## Q.1 Use Pandas to load and analyze a dataset (e.g., sum, mean, median)

In [119]:
df=pd.read_csv("C:\\Users\\KMC\\Desktop\\pandas\\placement.csv")

In [121]:
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [125]:
print(df.columns)

Index(['cgpa', 'resume_score', 'placed'], dtype='object')


In [149]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [142]:
# sum
print(df['resume_score'].sum()) 
print(df.sum(numeric_only=True))

693.05
cgpa            694.22
resume_score    693.05
placed           50.00
dtype: float64


In [144]:
# mean
print(df['placed'].mean()) 
print(df.mean(numeric_only=True))

0.5
cgpa            6.9422
resume_score    6.9305
placed          0.5000
dtype: float64


In [146]:
# median
print(df['cgpa'].median()) 
print(df.median(numeric_only=True))

6.62
cgpa            6.620
resume_score    7.055
placed          0.500
dtype: float64


## 2. Perform matrix operations using NumPy (e.g., addition, multiplication)

In [153]:
# Create Matrices (2D NumPy Arrays)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [157]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [163]:
# Matrix Addition
C = A + B
print("Addition:\n", C)

Addition:
 [[ 6  8]
 [10 12]]


In [165]:
# Matrix Subtraction
D = A - B
print("Subtraction:\n", D)

Subtraction:
 [[-4 -4]
 [-4 -4]]


In [169]:
#Matrix Multiplication
F = np.dot(A, B)
print("Matrix Multiplication:\n", F)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [171]:
# Identity Matrix
I = np.identity(2)
print("Identity Matrix:\n", I)

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


## 3. Use Pandas to filter, group, and sort data in a DataFrame

In [176]:
# Import Pandas and load your dataset
import pandas as pd

df  = pd.read_csv("C:\\Users\\KMC\\Desktop\\pandas\\covid_toy.csv")

In [178]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [180]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [194]:
#Filter the data
#Patients with fever over 100°F
high_fever = df[df['fever'] > 100]
print(high_fever.sample(5))

    age  gender  fever   cough       city has_covid
83   17  Female  104.0    Mild    Kolkata        No
72   83  Female  101.0    Mild    Kolkata        No
97   20  Female  101.0    Mild  Bangalore        No
79   48  Female  103.0    Mild    Kolkata       Yes
74   34  Female  104.0  Strong      Delhi        No


In [200]:
#Female patients with COVID
female_covid = df[(df['gender'] == 'Female') & (df['has_covid'] == 'Yes')]
print(female_covid.head())



    age  gender  fever   cough       city has_covid
5    84  Female    NaN    Mild  Bangalore       Yes
7    20  Female    NaN  Strong     Mumbai       Yes
11   65  Female   98.0    Mild     Mumbai       Yes
16   69  Female  103.0    Mild    Kolkata       Yes
18   64  Female   98.0    Mild  Bangalore       Yes


In [202]:
# Group the data

In [204]:
#Count of COVID cases by city

grouped_by_city = df[df['has_covid'] == 'Yes'].groupby('city').size()
print(grouped_by_city)

city
Bangalore    13
Delhi         9
Kolkata      15
Mumbai        8
dtype: int64


In [206]:
#Average age of patients by gender

avg_age_by_gender = df.groupby('gender')['age'].mean()
print(avg_age_by_gender)


gender
Female    43.847458
Male      44.756098
Name: age, dtype: float64


In [208]:
# Sort the data

In [210]:
sorted_by_fever = df.sort_values(by='fever', ascending=False)
print(sorted_by_fever)

    age  gender  fever   cough       city has_covid
62   56  Female  104.0  Strong  Bangalore       Yes
95   12  Female  104.0    Mild  Bangalore        No
83   17  Female  104.0    Mild    Kolkata        No
28   16    Male  104.0    Mild    Kolkata        No
74   34  Female  104.0  Strong      Delhi        No
..  ...     ...    ...     ...        ...       ...
29   34  Female    NaN  Strong     Mumbai       Yes
41   82    Male    NaN    Mild    Kolkata       Yes
56   71    Male    NaN  Strong    Kolkata        No
91   38    Male    NaN    Mild      Delhi       Yes
94   79    Male    NaN  Strong    Kolkata       Yes

[100 rows x 6 columns]
